spring:
  application:
    name: cloud-platform-heiden-pub
  datasource:
    url: jdbc:mysql://${MYSQL_IP:127.0.0.1}:${MYSQL_PORT:3306}/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 300 #最大连接池数量
    initialSize: 5 #初始化时建立物理连接的个数
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    minIdle: 10 #最小连接池数量
    timeBetweenEvictionRunsMillis: 60000 #Destroy线程会检测连接的间隔时间
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。
    testOnBorrow: false # 申请连接时执行validationQuery检测连接是否有效， 做了这个配置会降低性能。
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true #是否缓存preparedStatement，也就是PSCache
    maxOpenPreparedStatements: 20
    defaultAutoCommit: true
    removeAbandoned: true #对于长时间不使用的连接强制关闭
    removeAbandonedTimeout: 600 #超过10分钟开始关闭空闲连接,秒
    logAbandoned: true  #将当前关闭动作记录到日志    
#redis 配置
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1 
    timeout: 3600
  http:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
server:
  port: 8081
  tomcat:
    accept-count: 1000 
    max-threads: 1000
    max-connections: 2000
#系统自定义的配置
system:
  sysName: dbp
  internal:
    show: true #显示内部错误信息
jwt:
  token:
    header: token
    secret: sssshhhh!
    expiration: 604800
eureka:
  client:
    enabled: true
    service-url:
     defaultZone: ${EUREKA_LIST:http://127.0.0.1:8761/eureka/}

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  filter:
   metadata:
     enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

